import type { Article } from "./types";

export const articles: Article[] = [
  {
    slug: "menopoz-nedir",
    title: "Menopoz nedir? Vücudunuzda neler değişir?",
    excerpt:
      "Menopoz, adetin kalıcı olarak durmasıdır. Bu yazıda tanımı, perimenopozdan farkı ve vücutta sık görülen değişimleri sade bir dille anlatıyoruz.",
    category: "Menopoz",
    tags: ["menopoz", "perimenopoz", "hormon", "adet"],
    relatedSlugs: [
      "perimenopoz-nedir",
      "sicak-basmasi-neden-olur",
      "menopozda-dogru-bilinen-yanlislar",
    ],
    readingMinutes: 8,
    publishedAt: "2026-03-12",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    featured: true,
    body: [
      "Menopoz, 12 ay boyunca adet görmemenizle tanımlanan doğal bir geçiştir. Tek bir gün değil, yıllara yayılabilen hormonal bir süreçtir.",
      "Yumurtalıklar zamanla daha az östrojen ve progesteron üretir. Bu değişim sıcak basması, uyku bozulması, ruh hali dalgalanması veya vajinal kuruluk gibi belirtilere yol açabilir. Her kadında aynı belirtiler görülmez.",
      "Perimenopoz, menopoza giden geçiş dönemidir. Adetler düzensizleşebilir, bazı aylar yoğun, bazı aylar hafif olabilir. Menopoz ise adetin kalıcı olarak durduğu noktadır. Menopoz sonrası dönemde kemik, kalp-damar ve pelvik sağlık uzun vadede öne çıkar.",
      "Menopoz bir hastalık değildir. Yine de belirtiler günlük yaşamı zorlaştırıyorsa veya kanama düzeniniz değiştiyse bir kadın hastalıkları ve doğum uzmanına danışmak önemlidir. Özellikle menopoz sonrası kanama mutlaka değerlendirilmelidir.",
      "Bu belirti menopoz döneminde görülebilir. Ancak farklı nedenleri de olabilir. Kendi kendinize tanı koymayın; özellikle beklenmedik kanama, şiddetli ağrı veya nefes darlığı gibi durumlarda hekiminize başvurun.",
    ],
    references: [
      {
        title: "Menopause",
        source: "World Health Organization",
        url: "https://www.who.int/news-room/fact-sheets/detail/menopause",
        year: "2024",
      },
      {
        title: "The 2022 hormone therapy position statement",
        source: "The Menopause Society (NAMS)",
        year: "2022",
      },
    ],
  },
  {
    slug: "perimenopoz-nedir",
    title: "Perimenopoz: Menopoza geçiş döneminde neler olur?",
    excerpt:
      "Adetleriniz değişmeye başladıysa perimenopoz döneminde olabilirsiniz. Belirtileri, ne kadar sürebileceğini ve ne zaman doktora gitmeniz gerektiğini öğrenin.",
    category: "Menopoz",
    tags: ["perimenopoz", "adet düzensizliği", "menopoz"],
    relatedSlugs: ["menopoz-nedir", "sicak-basmasi-neden-olur", "menopozda-uyku"],
    readingMinutes: 7,
    publishedAt: "2026-03-18",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    featured: true,
    body: [
      "Perimenopoz, menopoza giden geçiş dönemidir. Birçok kadında 40’lı yaşlarda başlar; bazen daha erken, bazen daha geç olabilir.",
      "Bu dönemde yumurtlama daha düzensiz hale gelebilir. Adet aralıkları kısalabilir veya uzayabilir. Sıcak basması, gece terlemesi, uyku sorunu ve ruh hali değişimleri görülebilir.",
      "Perimenopoz birkaç yıl sürebilir. Süreyi önceden net söylemek mümkün değildir. Kan tahlili tek başına her zaman tanı koydurmaz; hekim öykü, belirtiler ve muayeneyi birlikte değerlendirir.",
      "Şu durumlarda gecikmeden hekime başvurun: çok yoğun kanama, adetler arasında lekelenme, 12 aydan sonra yeniden kanama, şiddetli çarpıntı, göğüs ağrısı veya günlük yaşamı bozan ruh hali değişimleri.",
    ],
    references: [
      {
        title: "Perimenopause",
        source: "The Menopause Society",
        year: "2023",
      },
      {
        title: "NICE guideline NG23: Menopause",
        source: "National Institute for Health and Care Excellence",
        url: "https://www.nice.org.uk/guidance/ng23",
        year: "2024",
      },
    ],
  },
  {
    slug: "sicak-basmasi-neden-olur",
    title: "Menopozda sıcak basması neden olur?",
    excerpt:
      "Sıcak basması, ani ısı ve terleme dalgasıdır. Neden oluştuğunu, ne kadar sürebileceğini ve yaşamı kolaylaştırabilecek yaklaşımları anlatıyoruz.",
    category: "Menopoz",
    tags: ["sıcak basması", "vazomotor", "gece terlemesi"],
    relatedSlugs: ["menopoz-nedir", "menopozda-uyku", "hormon-tedavisi-nedir"],
    readingMinutes: 6,
    publishedAt: "2026-04-02",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    featured: true,
    body: [
      "Sıcak basması, yüz, boyun ve göğüste ani bir sıcaklık hissi, kızarma ve terleme ile kendini gösterebilir. Gece olursa uyku bölünür; buna sıkça gece terlemesi denir.",
      "Östrojen düzeyindeki değişimler vücudun ısı ayarını etkileyebilir. Kafein, alkol, baharatlı yiyecekler, sıcak ortam ve stres bazı kadınlarda atakları tetikleyebilir.",
      "Yaşam tarzı adımları herkeste yeterli olmayabilir. Katmanlı giyinmek, odayı serin tutmak, tetikleyicileri gözlemlemek ve düzenli hareket etmek bazı kişilerde şikâyeti azaltabilir.",
      "Sık ve şiddetli sıcak basmaları yaşam kalitesini bozuyorsa hekimle seçenekleri konuşmak gerekir. Hormon tedavisi herkes için uygun değildir; karar kişiye özel risk ve fayda değerlendirmesiyle alınır.",
      "Bu belirti menopoz döneminde görülebilir. Ancak farklı nedenleri de olabilir. Açıklanamayan kilo kaybı, çarpıntı veya tiroit şüphesi varsa ayrıca değerlendirilmelidir.",
    ],
    references: [
      {
        title: "Nonhormone therapy for menopause symptoms",
        source: "The Menopause Society",
        year: "2023",
      },
      {
        title: "Menopausal symptoms",
        source: "ACOG",
        year: "2024",
      },
    ],
  },
  {
    slug: "menopozda-uyku",
    title: "Menopozda uyku neden bozulur?",
    excerpt:
      "Gece terlemesi, kaygı ve ritm değişiklikleri uykuyu bozabilir. Uyku hijyeni ve ne zaman yardım isteneceği üzerine pratik bir rehber.",
    category: "Menopoz",
    tags: ["uyku", "gece terlemesi", "menopoz"],
    relatedSlugs: ["sicak-basmasi-neden-olur", "menopozda-ruh-hali"],
    readingMinutes: 6,
    publishedAt: "2026-04-08",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Menopoz döneminde uykuya dalmak veya uykuyu sürdürmek zorlaşabilir. Gece terlemesi, sık idrara kalkma ve zihin yorgunluğu uykuyu bölebilir.",
      "Düzenli yatış saati, yatak odasını serin tutmak, geç saatte kafein ve ağır yemekten kaçınmak bazı kadınlarda fark yaratır. Ekranı yatmadan önce azaltmak da faydalı olabilir.",
      "Kronik uykusuzluk, gündüz güvenliğinizi veya ruh halinizi bozuyorsa bu bir irade meselesi değildir. Hekiminiz uyku, ruh sağlığı ve hormonal değişimleri birlikte değerlendirebilir.",
    ],
    references: [
      {
        title: "Sleep and menopause",
        source: "The Menopause Society",
        year: "2023",
      },
    ],
  },
  {
    slug: "menopozda-ruh-hali",
    title: "Menopoz döneminde ruh hali değişimleri",
    excerpt:
      "Sinirlilik, kaygı veya içe kapanma menopoz döneminde görülebilir. Ne zaman normal kabul edilebileceğini ve ne zaman destek isteneceğini konuşuyoruz.",
    category: "Menopoz",
    tags: ["ruh hali", "kaygı", "depresyon"],
    relatedSlugs: ["menopozda-uyku", "perimenopoz-nedir"],
    readingMinutes: 6,
    publishedAt: "2026-04-14",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Hormonal dalgalanma, uyku kaybı ve yaşam dönemindeki değişimler ruh halini etkileyebilir. Bu, duygularınızın ‘abartılı’ olduğu anlamına gelmez.",
      "Destekleyici sohbet, hareket, gün ışığı ve sosyal bağ bazı kişilerde iyi gelir. Ancak iki haftadan uzun süren çökkünlük, umutsuzluk, işlev kaybı veya kendine zarar düşünceleri acil profesyonel destek gerektirir.",
      "Ruh sağlığı desteği zayıflık değildir. Kadın hastalıkları uzmanı, aile hekimi veya ruh sağlığı profesyoneli birlikte yol gösterebilir.",
    ],
    references: [
      {
        title: "Depression and menopause",
        source: "ACOG Committee Opinion",
        year: "2018",
      },
    ],
  },
  {
    slug: "hormon-tedavisi-nedir",
    title: "Menopozda hormon tedavisi nedir, kimler için düşünülür?",
    excerpt:
      "Hormon tedavisi belirtileri azaltabilir; ancak herkes için uygun değildir. Fayda, risk ve bireysel karar sürecini sadeleştiriyoruz.",
    category: "Menopoz",
    tags: ["hormon tedavisi", "östrojen", "MHT"],
    relatedSlugs: ["sicak-basmasi-neden-olur", "menopoz-nedir"],
    readingMinutes: 9,
    publishedAt: "2026-04-20",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    featured: true,
    body: [
      "Menopoz hormon tedavisi (MHT), düşük östrojeni yerine koymaya yönelik tıbbi bir seçenektir. Sıcak basması ve gece terlemesi gibi vazomotor belirtilerde etkili olabilir. Rahmi olan kadınlarda genellikle progesteron da eklenir.",
      "Tedavi kişiye özeldir. Yaş, menopozdan geçen süre, pıhtı öyküsü, meme kanseri öyküsü, karaciğer hastalığı ve sigara kullanımı kararı değiştirir.",
      "İnternetten veya arkadaş tavsiyesiyle hormon başlatmak güvenli değildir. Doz, yol (hap, yama, jel) ve süre hekimle planlanır. Belirli aralıklarla yeniden değerlendirilir.",
      "Bu yazı tanı veya reçete niteliği taşımaz. Hormon tedavisinin sizin için uygun olup olmadığını yalnızca sizi değerlendiren hekim söyleyebilir.",
    ],
    references: [
      {
        title: "The 2022 hormone therapy position statement of The Menopause Society",
        source: "The Menopause Society",
        year: "2022",
      },
      {
        title: "NICE NG23 Menopause: identification and management",
        source: "NICE",
        year: "2024",
      },
    ],
  },
  {
    slug: "menopozda-kemik-sagligi",
    title: "Menopozda kemik sağlığı neden öne çıkar?",
    excerpt:
      "Östrojen azalınca kemik kaybı hızlanabilir. Beslenme, hareket ve tarama hakkında bilinmesi gerekenler.",
    category: "Menopoz",
    tags: ["kemik", "osteoporoz", "D vitamini"],
    relatedSlugs: ["menopoz-nedir", "menopozda-beslenme"],
    readingMinutes: 6,
    publishedAt: "2026-05-01",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Östrojen kemik yenilenmesinde rol oynar. Menopoz sonrası kemik mineral yoğunluğu daha hızlı azalabilir. Bu, herkeste kırık olacağı anlamına gelmez; risk kişiye göre değişir.",
      "Yeterli kalsiyum ve D vitamini, ağırlık bindiren egzersizler ve sigarayı bırakmak kemik sağlığını destekleyebilir. Takviye kararı hekim veya diyetisyenle verilmelidir.",
      "Ailede kalça kırığı, uzun süre kortizon kullanımı veya erken menopoz varsa tarama konuşulmalıdır. Kendi başınıza yüksek doz takviye başlatmayın.",
    ],
    references: [
      {
        title: "Osteoporosis prevention, screening, and diagnosis",
        source: "ACOG Clinical Practice Guideline",
        year: "2021",
      },
    ],
  },
  {
    slug: "menopozda-beslenme",
    title: "Menopoz döneminde beslenme: Ne işe yarar, ne abartılır?",
    excerpt:
      "Tek bir ‘menopoz diyeti’ yoktur. Kanıta yakın duran, abartısız bir beslenme çerçevesi.",
    category: "Menopoz",
    tags: ["beslenme", "kilo", "lif"],
    relatedSlugs: ["menopozda-kemik-sagligi", "menopoz-ve-egzersiz"],
    readingMinutes: 7,
    publishedAt: "2026-05-06",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Menopozda metabolizma ve vücut dağılımı değişebilir. Mucize detoks veya tek besinle ‘hormon dengeleme’ vaatleri bilimsel değildir.",
      "Sebze, meyve, tam tahıl, protein ve sağlıklı yağlardan oluşan düzenli bir tabak; şekerli içecekleri azaltmak ve alkolü sınırlamak genel sağlık için daha sağlam bir temeldir.",
      "Soya, keten tohumu veya bitkisel takviyeler bazı kadınlarda konuşulur; etkileri kişiden kişiye değişir ve ilaçlarla etkileşebilir. Takviyeyi hekiminize söyleyin.",
    ],
    references: [
      {
        title: "Healthy diet",
        source: "World Health Organization",
        year: "2020",
      },
    ],
  },
  {
    slug: "menopoz-ve-egzersiz",
    title: "Menopoz ve hareket: Ne kadar, nasıl?",
    excerpt:
      "Yürümek, kuvvet ve denge çalışmaları sıcak basması, uyku ve kemik için destekleyici olabilir.",
    category: "Menopoz",
    tags: ["egzersiz", "hareket", "kemik"],
    relatedSlugs: ["menopozda-beslenme", "menopozda-kemik-sagligi"],
    readingMinutes: 5,
    publishedAt: "2026-05-10",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Düzenli hareket ruh hali, uyku, kilo ve kemik sağlığına katkı sağlayabilir. Başlamak için spor salonu şart değildir; tempolu yürüyüş birçok kişi için iyi bir ilk adımdır.",
      "Haftanın çoğu günü hareket, iki-üç gün hafif kuvvet çalışması ve denge egzersizleri genel öneri çerçevesindedir. Eklem ağrısı, kalp hastalığı veya yeni başlayan göğüs ağrısı varsa önce hekime danışın.",
    ],
    references: [
      {
        title: "WHO guidelines on physical activity and sedentary behaviour",
        source: "World Health Organization",
        year: "2020",
      },
    ],
  },
  {
    slug: "menopozda-cinsel-saglik",
    title: "Menopozda cinsel sağlık ve vajinal kuruluk",
    excerpt:
      "İstek, kayganlık ve rahatlık değişebilir. Utanmadan konuşulabilecek seçenekler ve ne zaman hekime gidileceği.",
    category: "Cinsel Sağlık",
    tags: ["vajinal kuruluk", "cinsel sağlık", "GSM"],
    relatedSlugs: ["menopoz-nedir", "pelvik-saglik"],
    readingMinutes: 7,
    publishedAt: "2026-05-16",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Östrojen azalınca vajinal doku daha ince ve daha az kaygan olabilir. Bu durum cinsel ilişkide ağrı, yanma veya idrar yolu şikâyetleriyle birlikte görülebilir.",
      "Nemlendirici ve kayganlaştırıcılar bazı kadınlarda rahatlama sağlar. Lokal östrojen gibi tıbbi seçenekler hekim değerlendirmesiyle düşünülebilir. Cinsel istekteki değişim yalnızca hormonla açıklanmaz; uyku, ilişki, ağrı ve ruh hali de rol oynar.",
      "Kanama, kötü kokulu akıntı, ateş veya ani şişlik varsa gecikmeden hekime başvurun. Cinsel sağlık utanç konusu değildir; konuşulabilir ve tedavi edilebilir.",
    ],
    references: [
      {
        title: "Genitourinary syndrome of menopause",
        source: "The Menopause Society",
        year: "2020",
      },
    ],
  },
  {
    slug: "menopozda-dogru-bilinen-yanlislar",
    title: "Menopozda doğru bilinen yanlışlar",
    excerpt:
      "‘Her kadında sıcak basması olur’ dan ‘hormon tedavisi herkese zararlıdır’a kadar sık duyulan iddiaları sakinleştiriyoruz.",
    category: "Menopoz",
    tags: ["mitler", "yanlış bilgi", "menopoz"],
    relatedSlugs: ["hormon-tedavisi-nedir", "menopoz-nedir"],
    readingMinutes: 6,
    publishedAt: "2026-05-22",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    featured: true,
    body: [
      "Yanlış: Menopoz bir gecede olur. Doğrusu: Çoğu kadında yıllara yayılan bir geçiştir.",
      "Yanlış: Belirti yoksa menopoz yoktur. Doğrusu: Bazı kadınlar az belirti yaşar; adetin 12 ay kesilmesi tanısal tanımdır.",
      "Yanlış: Hormon tedavisi herkese zararlıdır. Doğrusu: Risk ve fayda kişiye, zamana ve geçmişe göre değişir. Karar toplu korkuyla değil, hekimle verilir.",
      "Yanlış: Bitkisel ürünler her zaman güvenlidir. Doğrusu: Bitkisel olması zararsız olduğu anlamına gelmez; ilaç etkileşimi olabilir.",
      "Forumdaki deneyimler değerli olabilir ama başkasının ilacı sizin ilacınız değildir.",
    ],
    references: [
      {
        title: "Menopause: identification and management",
        source: "NICE NG23",
        year: "2024",
      },
    ],
  },
  {
    slug: "gebelikte-mide-bulantisi",
    title: "Gebelikte mide bulantısı: Ne beklemeli, ne zaman doktora gitmeli?",
    excerpt:
      "Bulantı sık görülür ama ‘normal’ her şeyi kapsamaz. Hafifletme yolları ve uyarı işaretleri.",
    category: "Gebelik",
    tags: ["bulantı", "1. trimester", "beslenme"],
    relatedSlugs: ["gebelik-belirtileri", "gebelikte-beslenme", "gebelikte-ne-zaman-doktora"],
    readingMinutes: 7,
    publishedAt: "2026-02-04",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    featured: true,
    body: [
      "Gebeliğin ilk aylarında bulantı ve kusma yaygındır. Genellikle sabahla sınırlı değildir; gün içinde dalgalanabilir. Birçok kadında ikinci trimesterde hafifler.",
      "Sık küçük öğünler, sade karbonhidratlar, sıvıyı yudum yudum almak ve tetikleyici kokulardan uzak durmak bazı kişilerde işe yarar. B6 vitamini veya ilaç ihtiyacı hekim kararıdır; kendi başınıza ilaç başlatmayın.",
      "Günde birkaç kez kusma, idrar yapamama, baş dönmesi, kilo kaybı veya kanlı kusma varsa gecikmeden sağlık kuruluşuna başvurun. Hipermezis gravidarum tıbbi değerlendirme gerektirir.",
    ],
    references: [
      {
        title: "Nausea and vomiting of pregnancy",
        source: "ACOG Practice Bulletin",
        year: "2018",
      },
      {
        title: "Antenatal care",
        source: "T.C. Sağlık Bakanlığı",
        year: "2018",
      },
    ],
  },
  {
    slug: "gebelik-belirtileri",
    title: "Gebelik belirtileri: İlk haftalarda neler hissedilebilir?",
    excerpt:
      "Adet gecikmesi, germe, yorgunluk ve koku hassasiyeti sık anlatılır. Test ve hekim kontrolünün yeri.",
    category: "Gebelik",
    tags: ["gebelik belirtileri", "test", "1. trimester"],
    relatedSlugs: ["gebelikte-mide-bulantisi", "gebelik-oncesi-hazirlik"],
    readingMinutes: 6,
    publishedAt: "2026-01-22",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Adet gecikmesi en bilinen işarettir. Göğüslerde hassasiyet, yorgunluk, sık idrara çıkma ve koku hassasiyeti de görülebilir. Hiçbiri tek başına gebelik kanıtı değildir.",
      "Ev testi genellikle adet gecikmesinden sonra daha güvenilir sonuç verir. Pozitif testten sonra prenatal takibe başlamak için kadın hastalıkları ve doğum uzmanına başvurun.",
      "Şiddetli karın ağrısı, omuz ağrısı, bayılma veya yoğun kanama acil değerlendirme gerektirir. Dış gebelik gibi durumlar erken dönemde ortaya çıkabilir.",
    ],
    references: [
      {
        title: "Early pregnancy",
        source: "NICE guideline NG126",
        year: "2019",
      },
    ],
  },
  {
    slug: "gebelik-oncesi-hazirlik",
    title: "Gebelik öncesi hazırlık: Kontroller, folik asit ve ilaçlar",
    excerpt:
      "Planlı bir gebelikte folik asit, aşılar, kronik hastalıklar ve ilaç gözden geçirmesi neden önemlidir?",
    category: "Gebelik",
    tags: ["folik asit", "gebelik planlama", "aşı"],
    relatedSlugs: ["gebelikte-beslenme", "gebelik-belirtileri"],
    readingMinutes: 8,
    publishedAt: "2026-01-10",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    featured: true,
    body: [
      "Gebelik planlıyorsanız folik asit çoğu kadında nöral tüp defekti riskini azaltmak için önerilir. Doz ve süre hekiminize göre değişebilir; özellikle epilepsi, diyabet veya önceki nöral tüp defekti öyküsünde doz farklı olabilir.",
      "Kızamıkçık bağışıklığı, hepatit B, tetanoz ve influenza gibi aşılar gebelik öncesi konuşulabilir. Canlı aşılar gebelikte uygun olmayabilir.",
      "Düzenli kullandığınız ilaçları, bitkisel ürünleri ve vitaminleri listeleyin. Bazı sivilce, tansiyon veya ağrı ilaçları gebelikte değiştirilir. İlacı kendi başınıza kesmeyin; hekimle planlayın.",
      "Sigara, alkol ve uyuşturucu maddelerden uzak durmak hem gebelik öncesi hem gebelikte önemlidir.",
    ],
    references: [
      {
        title: "Preconception care",
        source: "World Health Organization",
        year: "2013",
      },
      {
        title: "Folate and pregnancy",
        source: "CDC",
        year: "2024",
      },
    ],
  },
  {
    slug: "gebelikte-beslenme",
    title: "Gebelikte beslenme: Temel ilkeler ve kaçınılacaklar",
    excerpt:
      "İki kişilik yemek gerekmez. Güvenli gıda, kafein ve takviye hakkında sakin bir çerçeve.",
    category: "Gebelik",
    tags: ["beslenme", "listeria", "kafein"],
    relatedSlugs: ["gebelikte-mide-bulantisi", "gebelik-oncesi-hazirlik"],
    readingMinutes: 7,
    publishedAt: "2026-02-12",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Gebelikte ihtiyaç artar ama ‘iki kişilik tabak’ gerekmez. Çeşitli, düzenli öğünler ve yeterli sıvı çoğu kişi için temeldir.",
      "Pastörize olmamış süt ürünleri, çiğ veya az pişmiş et-yumurta, ve bazı hazır salatalar enfeksiyon riski nedeniyle kaçınılması önerilenler arasındadır. Kafein alımını hekiminizin önerdiği sınıra çekmek iyi bir hedeftir.",
      "Balık yararlı olabilir; yüksek cıvalı türlerden kaçınılır. Takviyeleri ‘doğal’ olduğu için serbest görmeyin. Multivitamin ve demir ihtiyacı kişiye göre değişir.",
    ],
    references: [
      {
        title: "Nutrition during pregnancy",
        source: "ACOG",
        year: "2023",
      },
    ],
  },
  {
    slug: "gebelikte-ne-zaman-doktora",
    title: "Gebelikte hangi belirtilerde doktora başvurmalıyım?",
    excerpt:
      "Rahatsızlık ile acil uyarıyı ayırt etmek zordur. Bu liste tanı koymaz; yönlendirir.",
    category: "Gebelik",
    tags: ["acil", "uyarı işaretleri", "gebelik"],
    relatedSlugs: ["gebelikte-mide-bulantisi", "dogum-belirtileri"],
    readingMinutes: 6,
    publishedAt: "2026-02-20",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Aşağıdakiler acil değerlendirme gerektirir: vajinal kanama, su gelmesi, şiddetli baş ağrısı, görme bulanıklığı, şiddetli karın veya omuz ağrısı, ateş, ağrılı idrar, bebek hareketlerinde belirgin azalma, nefes darlığı veya bayılma.",
      "Bu liste tam değildir. ‘Bir şeyler yanlış’ hissiniz varsa beklemeyin. 112’yi aramak veya acile gitmek abartı değildir.",
      "Bu platform tanı koymaz ve acil yardım sunmaz.",
    ],
    references: [
      {
        title: "Warning signs in pregnancy",
        source: "WHO recommendations on antenatal care",
        year: "2016",
      },
    ],
  },
  {
    slug: "dogum-belirtileri",
    title: "Doğum belirtileri: Doğum ne zaman başlar?",
    excerpt:
      "Düzenli kasılmalar, suyun gelmesi ve mukus tıkaç. Braxton Hicks ile gerçek eylemi ayırt etmeye yardım.",
    category: "Doğum",
    tags: ["doğum belirtileri", "kasılma", "su gelmesi"],
    relatedSlugs: ["vajinal-dogum-ve-sezaryen", "hastane-cantasi", "dogum-plani"],
    readingMinutes: 8,
    publishedAt: "2026-03-01",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    featured: true,
    body: [
      "Gerçek doğum eyleminde kasılmalar genellikle zamanla sıklaşır, güçlenir ve dinlenmekle geçmez. Braxton Hicks denilen hazırlık kasılmaları ise düzensiz olabilir ve konum değiştirince hafifleyebilir.",
      "Suyun gelmesi, vajinal kanama, şiddetli ve sürekli karın ağrısı veya bebek hareketlerinde azalma halinde hekiminizin tarif ettiği yola göre hastaneye başvurun.",
      "Doğumun tam olarak hangi dakikada ‘başladığını’ evde tek başına teşhis etmek her zaman mümkün değildir. Şüphede kalırsanız arayıp sorun; bu bir zayıflık değil, güvenliktir.",
    ],
    references: [
      {
        title: "Intrapartum care",
        source: "WHO",
        year: "2018",
      },
      {
        title: "Labor induction and labor symptoms",
        source: "ACOG",
        year: "2022",
      },
    ],
  },
  {
    slug: "vajinal-dogum-ve-sezaryen",
    title: "Vajinal doğum ve sezaryen: Yöntemler nasıl konuşulur?",
    excerpt:
      "Tek doğru doğum yoktur. Tıbbi gerekçe, tercih ve güvenlik nasıl bir arada düşünülür?",
    category: "Doğum",
    tags: ["vajinal doğum", "sezaryen", "doğum yöntemleri"],
    relatedSlugs: ["dogum-belirtileri", "dogum-plani", "dogum-korkusu"],
    readingMinutes: 8,
    publishedAt: "2026-03-08",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Vajinal doğum ve sezaryen farklı yollardır. Karar; gebeliğin gidişi, bebeğin duruşu, önceki ameliyatlar ve acil durumlarla şekillenir.",
      "Sezaryen hayat kurtaran bir ameliyat olabilir. Gereksiz sezaryen ise ek riskler taşıyabilir. ‘Doğal olan her zaman daha iyidir’ veya ‘ameliyat her zaman daha güvenlidir’ gibi genellemeler yanıltıcıdır.",
      "Doğum planı bir talep listesi değil, hekimle yapılan bir konuşma zeminidir. Plan değişebilir; güvenlik önceliklidir.",
    ],
    references: [
      {
        title: "Caesarean birth",
        source: "NICE NG192",
        year: "2021",
      },
      {
        title: "Vaginal birth after cesarean",
        source: "ACOG",
        year: "2019",
      },
    ],
  },
  {
    slug: "dogum-korkusu",
    title: "Doğum korkusu: Konuşulabilir, yalnız yaşanmak zorunda değil",
    excerpt:
      "Korku zayıflık değildir. Bilgi, doğum planı ve ruh sağlığı desteği nasıl yardımcı olabilir?",
    category: "Doğum",
    tags: ["korku", "anksiyete", "doğuma hazırlık"],
    relatedSlugs: ["dogum-plani", "vajinal-dogum-ve-sezaryen"],
    readingMinutes: 6,
    publishedAt: "2026-03-15",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Doğum korkusu sık görülür. Önceki travma, belirsizlik, ağrı endişesi veya kontrol kaybı hissi rol oynayabilir.",
      "Güvenilir bilgi, doğum ekibiyle açık konuşma ve gerekirse ruh sağlığı desteği korkuyu yönetmeye yardım edebilir. Korkuyu bastırmak zorunda değilsiniz.",
      "Panik atak, uykusuzluk veya gebeliği erteleme düzeyinde kaçınma varsa profesyonel destek alın. Bu yazı terapi yerine geçmez.",
    ],
    references: [
      {
        title: "Fear of childbirth",
        source: "RCOG patient information",
        year: "2022",
      },
    ],
  },
  {
    slug: "dogum-plani",
    title: "Doğum planı nasıl hazırlanır?",
    excerpt:
      "Ağrı yönetimi, kimlerin odada olacağı, ten tene temas. Esnek, konuşulabilir bir plan.",
    category: "Doğum",
    tags: ["doğum planı", "hazırlık"],
    relatedSlugs: ["hastane-cantasi", "dogum-belirtileri"],
    readingMinutes: 5,
    publishedAt: "2026-03-19",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Doğum planı; tercihlerinizi hekiminiz ve doğum ekibine anlatmanın bir yoludur. Ağrı yönetimi, pozisyon, kimlerin yanınızda olacağı ve ilk ten tene temas gibi başlıklar konuşulabilir.",
      "Plan bir sözleşme değildir. Bebeğin veya sizin güvenliği için gidişat değişebilir. Esnek bir plan, hayal kırıklığını azaltır.",
    ],
    references: [
      {
        title: "Your baby's appearance and newborn procedures",
        source: "NHS",
        year: "2024",
      },
    ],
  },
  {
    slug: "hastane-cantasi",
    title: "Hastane çantası: Neleri ne zaman hazırlamalı?",
    excerpt:
      "Abartısız, pratik bir liste. Her eşya zorunlu değildir; sizin konforunuz önemlidir.",
    category: "Doğum",
    tags: ["hastane çantası", "hazırlık"],
    relatedSlugs: ["dogum-plani", "dogum-belirtileri"],
    readingMinutes: 5,
    publishedAt: "2026-03-21",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Kimlik, tetkik sonuçları, kan grubu bilgisi ve hekiminizin iletişim bilgisi çantanın en önemli parçasıdır. Rahat giysi, emzirme sütyeni, ped, şarj aleti ve bebeğin ilk kıyafetleri sık paketlenir.",
      "Hastanenin neler sağladığını önceden sorun. Başkasının devasa listesini bire bir kopyalamak zorunda değilsiniz.",
    ],
    references: [
      {
        title: "Packing for hospital",
        source: "NHS",
        year: "2024",
      },
    ],
  },
  {
    slug: "dogum-sonrasi-kanama",
    title: "Doğum sonrası kanama: Lohusa akıntısı ne zaman normaldir?",
    excerpt:
      "Loşi nedir, ne kadar sürer, hangi kanama acildir? Panik değil, net uyarılar.",
    category: "Doğum Sonrası",
    tags: ["loşi", "kanama", "lohusalık"],
    relatedSlugs: ["lohusalik-nedir", "ne-zaman-doktora-basvurmali"],
    readingMinutes: 7,
    publishedAt: "2026-04-01",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    featured: true,
    body: [
      "Doğumdan sonra loşi adı verilen vajinal akıntı beklenir. İlk günler kırmızımsı ve daha yoğundur; günler içinde pembe-kahverengi, sonra sarımsı-beyaza dönebilir. Süre kişiden kişiye değişir.",
      "Bir saatte birden fazla pedi ıslatan kanama, pıhtıların büyümesi, kötü koku, ateş, baş dönmesi veya bayılma acil durum olabilir. 112’yi arayın veya acile gidin.",
      "Bu yazı sizin kanamanızın ‘normal’ olduğunu söylemez. Şüphede acil bakımı tercih edin.",
    ],
    references: [
      {
        title: "Postpartum hemorrhage",
        source: "WHO",
        year: "2023",
      },
      {
        title: "Postnatal care",
        source: "NICE NG194",
        year: "2021",
      },
    ],
  },
  {
    slug: "lohusalik-nedir",
    title: "Lohusalık: Doğumdan sonraki haftalarda vücut ve duygu",
    excerpt:
      "Uyku bölünmesi, süt, kanama ve duygusal dalgalanma. Beklentiyi gerçekçi kılan bir bakış.",
    category: "Doğum Sonrası",
    tags: ["lohusalık", "emzirme", "uyku"],
    relatedSlugs: ["dogum-sonrasi-kanama", "dogum-sonrasi-ruhsal-degisimler", "emzirme"],
    readingMinutes: 7,
    publishedAt: "2026-04-05",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Lohusalık, doğumdan sonraki toparlanma dönemidir. Kanama, terleme, göğüs dolgunluğu, kas-iskelet ağrıları ve uykusuzluk sık anlatılır.",
      "Destek istemek lüks değildir. Beslenme, sıvı, dinlenme fırsatları ve takip randevuları toparlanmanın parçasıdır.",
      "Ateş, kötü kokulu akıntı, bacakta şişlik-kızarıklık, nefes darlığı, göğüs ağrısı veya kendine/bebekine zarar düşünceleri acil yardıma işarettir.",
    ],
    references: [
      {
        title: "Postnatal care",
        source: "NICE NG194",
        year: "2021",
      },
    ],
  },
  {
    slug: "emzirme",
    title: "Emzirme: Başlangıç, zorluklar ve ne zaman yardım istenmeli",
    excerpt:
      "Emzirme her zaman ‘içgüdüsel’ gitmez. Tutuş, çatlak, süt yeterli mi soruları ve destek.",
    category: "Doğum Sonrası",
    tags: ["emzirme", "süt", "laktasyon"],
    relatedSlugs: ["lohusalik-nedir", "dogum-sonrasi-ruhsal-degisimler"],
    readingMinutes: 7,
    publishedAt: "2026-04-09",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Emzirme öğrenilen bir süreçtir. İlk günlerde sık emzirme, doğru tutuş ve destek çoğu çift için fark yaratır. Ağrı sürekli ve şiddetliyse ‘alışır’ diye beklemeyin.",
      "Bebeğin yeterince beslendiğini idrar-kaka sayısı, kilo takibi ve uyanıklık gibi işaretlerle sağlık çalışanı değerlendirir. Forum önerisiyle formül veya bitkisel süt arttırıcı başlatmayın.",
      "Mastit şüphesi (kızarıklık, ateş, flu-like tablo) tıbbi değerlendirme ister. Emzirme hedefi kişiselleştirilebilir; her aile aynı yolu seçmek zorunda değildir.",
    ],
    references: [
      {
        title: "Infant and young child feeding",
        source: "World Health Organization",
        year: "2023",
      },
    ],
  },
  {
    slug: "dogum-sonrasi-ruhsal-degisimler",
    title: "Doğum sonrası ruhsal değişimler: Baby blues ve ötesi",
    excerpt:
      "İlk günlerdeki duygusal dalga ile depresyon/anksiyete farkı. Yardım istemek güçlülüktür.",
    category: "Doğum Sonrası",
    tags: ["ruh sağlığı", "depresyon", "anksiyete"],
    relatedSlugs: ["lohusalik-nedir", "ne-zaman-doktora-basvurmali"],
    readingMinutes: 7,
    publishedAt: "2026-04-12",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Doğumdan sonraki ilk günlerde ağlama, hassasiyet ve duygu dalgalanması sık görülür ve çoğu zaman kısa sürer. İki haftayı aşan çökkünlük, zevk alamama, aşırı kaygı, uykuya dalamama (bebek uyurken bile) veya zarar düşünceleri profesyonel destek gerektirir.",
      "Doğum sonrası depresyon karakter zayıflığı değildir. Tedavi edilebilir. Partner ve aile belirtileri ciddiye almalıdır.",
      "Kendinize veya bebeğe zarar verme düşünceniz varsa hemen 112’yi arayın veya acile gidin.",
    ],
    references: [
      {
        title: "Postnatal mental health",
        source: "NICE CG192",
        year: "2020",
      },
    ],
  },
  {
    slug: "ne-zaman-doktora-basvurmali",
    title: "Doğum sonrası: Ne zaman doktora başvurmalı?",
    excerpt:
      "Lohusalıkta beklenen rahatsızlık ile acil tabloyu ayıran sade bir yönlendirme.",
    category: "Doğum Sonrası",
    tags: ["acil", "lohusalık", "kontrol"],
    relatedSlugs: ["dogum-sonrasi-kanama", "dogum-sonrasi-ruhsal-degisimler"],
    readingMinutes: 5,
    publishedAt: "2026-04-16",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Acil başvuru: yoğun kanama, nefes darlığı, göğüs ağrısı, bacakta tek taraflı şişlik, ateş, şiddetli baş ağrısı, görme bozukluğu, nöbet, kötü kokulu akıntı, yara yerinde açılma veya ruhsal kriz.",
      "Rutin kontrol randevusunu ertelemeyin. Şikâyetiniz randevu gününü beklemiyorsa beklemeyin.",
    ],
    references: [
      {
        title: "Postnatal care",
        source: "NICE NG194",
        year: "2021",
      },
    ],
  },
  {
    slug: "pelvik-saglik",
    title: "Pelvik sağlık: Doğum sonrası ve menopozda taban kasları",
    excerpt:
      "Kaçırma, sarkma hissi ve ağrı konuşulabilir. Egzersiz herkese aynı reçete değildir.",
    category: "Jinekoloji",
    tags: ["pelvik taban", "idrar kaçırma", "fizyoterapi"],
    relatedSlugs: ["menopozda-cinsel-saglik", "lohusalik-nedir"],
    readingMinutes: 6,
    publishedAt: "2026-05-28",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Pelvik taban kasları mesane, bağırsak ve cinsel işlevde rol oynar. Doğum, kronik ıkınma ve östrojen azalması bu bölgeyi etkileyebilir.",
      "Kegel herkes için doğru başlangıç olmayabilir; bazı tablolarda gevşeme gerekir. Kalıcı kaçırma, tam boşalamama veya organ sarkması hissi varsa hekim veya pelvik fizyoterapist değerlendirmesi uygundur.",
    ],
    references: [
      {
        title: "Pelvic floor dysfunction",
        source: "NICE NG210",
        year: "2021",
      },
    ],
  },
  {
    slug: "adet-dongusu-temelleri",
    title: "Adet döngüsü: Hormonal sağlığın takvimi",
    excerpt:
      "Döngü yalnızca kanama günü değildir. Foliküler ve luteal dönem sade bir anlatımla.",
    category: "Adet Döngüsü",
    tags: ["adet", "hormon", "ovulasyon"],
    relatedSlugs: ["perimenopoz-nedir", "jinekolojik-kontroller"],
    readingMinutes: 6,
    publishedAt: "2026-01-08",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Adet döngüsü, beyin ve yumurtalıklar arasındaki hormon konuşmasıdır. Kanama, döngünün görünen parçasıdır; yumurtlama ve rahim içi tabakanın hazırlığı diğer parçalarıdır.",
      "Döngü uzunluğu kişiden kişiye değişir. Ani düzensizlik, çok yoğun kanama veya adetler arasında kanama değerlendirilmelidir. Menopoza yaklaşırken düzensizlik artabilir; yine de varsayımla geçmeyin.",
    ],
    references: [
      {
        title: "Menstruation in girls and adolescents",
        source: "ACOG Committee Opinion",
        year: "2015",
      },
    ],
  },
  {
    slug: "jinekolojik-kontroller",
    title: "Jinekolojik kontroller ve koruyucu sağlık",
    excerpt:
      "Smear, HPV, meme farkındalığı ve kanama değişiklikleri. Kontroller korku değil, bakım içindir.",
    category: "Koruyucu Sağlık",
    tags: ["smear", "HPV", "tarama"],
    relatedSlugs: ["adet-dongusu-temelleri", "menopoz-nedir"],
    readingMinutes: 6,
    publishedAt: "2026-01-16",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Koruyucu sağlık, şikâyet yokken de tarama ve danışmanlığı kapsar. Serviks taraması (smear/HPV) yaş ve önceki sonuçlara göre planlanır.",
      "Menopoz sonrası kanama, cinsel ilişkide ağrı, açıklanamayan kilo kaybı veya ele gelen kitle gecikmeden değerlendirilir. Tarama takviminizi hekiminizle kişiselleştirin.",
    ],
    references: [
      {
        title: "Cervical cancer screening",
        source: "WHO",
        year: "2021",
      },
    ],
  },
  {
    slug: "preeklampsi",
    title: "Preeklampsi: Gebelikte tansiyon neden önemlidir?",
    excerpt:
      "Genellikle 20. haftadan sonra görülen, tansiyon yüksekliğiyle seyreden bir gebelik durumu. Hangi belirtiler acildir?",
    category: "Gebelik",
    tags: ["preeklampsi", "tansiyon", "gebelik takibi"],
    relatedSlugs: ["gebelikte-ne-zaman-doktora", "gebelik-sekeri"],
    readingMinutes: 6,
    publishedAt: "2026-04-02",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Preeklampsi, gebeliğin genellikle ikinci yarısında ortaya çıkan, tansiyon yüksekliği ve bazı organlarda etkilenmeyle seyreden bir durumdur. Rutin kontrollerde tansiyon ve idrar takibinin bir nedeni budur.",
      "Bazen belirti vermeden başlar. Şiddetli baş ağrısı, görme bulanıklığı veya ışık çakmaları, sağ üst karın ya da mide ağzında ağrı, yüz ve ellerde ani şişlik, nefes darlığı acil değerlendirme gerektirir.",
      "Risk değerlendirmesi ve önleyici yaklaşımlar kişiye göre hekim tarafından planlanır. Kendi başınıza ilaç başlamayın; kontrollerinizi aksatmayın.",
    ],
    references: [
      { title: "Hypertension in pregnancy: diagnosis and management", source: "NICE NG133", year: "2019" },
      { title: "Gestational Hypertension and Preeclampsia", source: "ACOG Practice Bulletin 222", year: "2020" },
    ],
  },
  {
    slug: "gebelik-sekeri",
    title: "Gebelik şekeri (gestasyonel diyabet) nedir?",
    excerpt:
      "Şeker yükleme testi neden yapılır, sonuç yüksek çıkarsa neler konuşulur? Sakin bir çerçeve.",
    category: "Gebelik",
    tags: ["gebelik şekeri", "diyabetik gebelik", "şeker yükleme testi"],
    relatedSlugs: ["gebelikte-beslenme", "preeklampsi"],
    readingMinutes: 6,
    publishedAt: "2026-04-06",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Gestasyonel diyabet, gebelik sırasında ilk kez fark edilen kan şekeri yüksekliğidir. Gebelik hormonları insülinin etkisini azaltabildiği için sık görülür ve çoğu zaman belirti vermez.",
      "Tarama genellikle 24–28. haftalar arasında şeker yükleme testiyle yapılır; risk durumuna göre daha erken de planlanabilir. Test zamanı ve yöntemi hekiminizle belirlenir.",
      "Tanı konursa beslenme düzeni, hareket ve kan şekeri takibi ilk adımlardır; gerekirse hekim tedavi planlar. Doğumdan sonra da kontrol önerilir, çünkü ileride tip 2 diyabet riski artabilir.",
    ],
    references: [
      { title: "Diabetes in pregnancy: management from preconception to the postnatal period", source: "NICE NG3", year: "2020" },
      { title: "Gestational Diabetes Mellitus", source: "ACOG Practice Bulletin 190", year: "2018" },
    ],
  },
  {
    slug: "erken-dogum",
    title: "Erken doğum: Hangi belirtilere dikkat etmeli?",
    excerpt:
      "37. haftadan önce başlayan doğum eylemi. Uyarı işaretleri ve neden beklememek gerekir.",
    category: "Doğum",
    tags: ["erken doğum", "kasılma", "su gelmesi"],
    relatedSlugs: ["dogum-belirtileri", "gebelikte-ne-zaman-doktora"],
    readingMinutes: 5,
    publishedAt: "2026-04-10",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "37. gebelik haftası tamamlanmadan başlayan doğum eylemine erken doğum denir. Bazen belirgin bir neden bulunmaz; önceki erken doğum, çoğul gebelik ve bazı enfeksiyonlar riski artırabilir.",
      "Düzenli ve sıklaşan kasılmalar, kasıkta veya belde ritmik ağrı, pelvik baskı hissi, akıntıda belirgin değişiklik, sulu gelme veya kanama varsa beklemeden doğum hastanesine başvurun.",
      "Erken başvuru, hekimin bebeği ve sizi korumaya yönelik önlemleri zamanında planlayabilmesi için önemlidir.",
    ],
    references: [
      { title: "Preterm labour and birth", source: "NICE NG25", year: "2022" },
      { title: "Preterm birth fact sheet", source: "WHO", year: "2023" },
    ],
  },
  {
    slug: "dis-gebelik",
    title: "Dış gebelik (ektopik gebelik): Neden acildir?",
    excerpt:
      "Gebeliğin rahim dışında yerleşmesi. Erken dönemde hangi belirtilerde hemen başvurmalı?",
    category: "Gebelik",
    tags: ["dış gebelik", "ektopik gebelik", "erken gebelik"],
    relatedSlugs: ["gebelik-belirtileri", "kimyasal-gebelik"],
    readingMinutes: 5,
    publishedAt: "2026-04-14",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Dış gebelikte döllenmiş yumurta rahim içine değil, çoğunlukla tüplere yerleşir. Bu gebelik sağlıklı şekilde devam edemez ve tedavi gerektirir.",
      "Pozitif test sonrası tek taraflı kasık ağrısı, lekelenme veya kanama, omuz ucu ağrısı, baş dönmesi ya da bayılma hissi varsa beklemeden acile başvurun. Şiddetli ağrı ve bayılmada 112’yi arayın.",
      "Erken gebelikte ilk ultrason kontrolünün bir amacı da gebeliğin yerini görmektir. Tedavi seçenekleri hekim tarafından kişiye göre belirlenir.",
    ],
    references: [
      { title: "Ectopic pregnancy and miscarriage: diagnosis and initial management", source: "NICE NG126", year: "2023" },
      { title: "Diagnosis and Management of Ectopic Pregnancy", source: "RCOG Green-top Guideline 21", year: "2016" },
    ],
  },
  {
    slug: "kimyasal-gebelik",
    title: "Kimyasal gebelik: Test pozitif, sonra adet gördüm",
    excerpt:
      "Çok erken dönemde sonlanan gebelik sık görülür. Ne anlama gelir, ne zaman tekrar deneyebilirim?",
    category: "Gebelik",
    tags: ["kimyasal gebelik", "erken kayıp", "planlama"],
    relatedSlugs: ["gebelik-oncesi-hazirlik", "dis-gebelik"],
    readingMinutes: 5,
    publishedAt: "2026-04-18",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Kimyasal gebelik, gebelik testinin pozitif çıkmasından kısa süre sonra, ultrasonda kese görülmeden sonlanan çok erken bir gebelik kaybıdır. Sık görülür ve çoğu zaman tek seferliktir.",
      "Genellikle sizin yaptığınız ya da yapmadığınız bir şeyle ilgili değildir. Üzüntü hissetmek doğaldır; duygularınızı paylaşmak iyi gelebilir.",
      "Şiddetli ağrı, çok yoğun kanama veya ateş varsa hekime başvurun. Tekrarlayan kayıplarda hekim ek değerlendirme planlayabilir. Yeniden deneme zamanını hekiminizle konuşun.",
    ],
    references: [
      { title: "Recurrent pregnancy loss", source: "ESHRE Guideline", year: "2022" },
      { title: "Early Pregnancy Loss", source: "ACOG Practice Bulletin 200", year: "2018" },
    ],
  },
  {
    slug: "pkos",
    title: "Polikistik over sendromu (PKOS): Düzensiz adet ve gebelik planı",
    excerpt:
      "Düzensiz adet, sivilce, kıllanma ve yumurtlama sorunları. PKOS gebe kalmayı nasıl etkiler?",
    category: "Hormonal Sağlık",
    tags: ["PKOS", "PCOS", "adet düzensizliği", "yumurtlama"],
    relatedSlugs: ["adet-dongusu-temelleri", "gebelik-oncesi-hazirlik"],
    readingMinutes: 7,
    publishedAt: "2026-02-04",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    featured: true,
    body: [
      "PKOS, üreme çağındaki kadınlarda sık görülen hormonal bir durumdur. Seyrek veya düzensiz adet, androjen fazlalığına bağlı sivilce ya da kıllanma ve ultrasonda yumurtalıklarda çok sayıda küçük folikül tanıda değerlendirilen özelliklerdendir.",
      "Ultrasonda ‘kist’ görülmesi tek başına PKOS demek değildir; tanı, belirtiler ve tetkiklerle birlikte konur.",
      "PKOS olan birçok kadın gebe kalabilir; yumurtlama düzensiz olduğunda süreç uzayabilir. Yaşam tarzı düzenlemeleri ve gerekirse hekim tarafından planlanan tedaviler yardımcı olabilir. Kendi başınıza hormon ilacı kullanmayın.",
    ],
    references: [
      { title: "International evidence-based guideline for the assessment and management of PCOS", source: "Monash University / ESHRE", year: "2023" },
    ],
  },
  {
    slug: "miyom",
    title: "Miyom nedir? Gebeliği etkiler mi?",
    excerpt:
      "Rahmin iyi huylu kas tümörleri çok yaygındır. Ne zaman belirti verir, ne zaman tedavi konuşulur?",
    category: "Jinekoloji",
    tags: ["miyom", "rahim", "yoğun adet kanaması"],
    relatedSlugs: ["adet-dongusu-temelleri", "jinekolojik-kontroller"],
    readingMinutes: 6,
    publishedAt: "2026-02-10",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Miyomlar rahim kasından gelişen, iyi huylu oluşumlardır ve üreme çağında sık görülür. Birçoğu belirti vermez ve rutin muayenede tesadüfen fark edilir.",
      "Yoğun veya uzun adet kanaması, kasıkta baskı, sık idrara çıkma ya da kansızlık belirti olabilir. Miyomun yeri ve boyutu, gebelik planı ve şikâyetlere göre izlem veya tedavi konuşulur.",
      "Gebelikte miyomların çoğu sorunsuz seyreder; bazı durumlarda ağrı veya takip gerektiren durumlar olabilir. Gebelik planlıyorsanız hekiminizle önceden konuşun.",
    ],
    references: [
      { title: "Management of Symptomatic Uterine Leiomyomas", source: "ACOG Practice Bulletin 228", year: "2021" },
    ],
  },
  {
    slug: "endometriozis",
    title: "Endometriozis: ‘Adet ağrısı normaldir’ demeden önce",
    excerpt:
      "Günlük yaşamı engelleyen adet ağrısı, ilişkide ağrı ve gebe kalmada zorluk. Endometriozis ve adenomyozis.",
    category: "Jinekoloji",
    tags: ["endometriozis", "adenomyozis", "ağrılı adet", "ilişkide ağrı"],
    relatedSlugs: ["agrili-adet", "adet-dongusu-temelleri"],
    readingMinutes: 7,
    publishedAt: "2026-02-16",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Endometriozis, rahim iç tabakasına benzer dokunun rahim dışında bulunmasıdır. Adenomyozis ise bu dokunun rahim kası içinde yer almasıdır. İkisi de ağrı ve yoğun kanamayla ilişkili olabilir.",
      "Okul ya da işe gitmeyi engelleyen adet ağrısı, cinsel ilişkide derin ağrı, adet dönemlerinde bağırsak veya idrar yakınmaları ve gebe kalmada zorluk değerlendirme gerektirir.",
      "Tanı süreci zaman alabilir; şikâyetlerinizi not etmek görüşmeyi kolaylaştırır. Tedavi; ağrı, yaş ve gebelik planına göre hekim tarafından kişiselleştirilir.",
    ],
    references: [
      { title: "Endometriosis guideline", source: "ESHRE", year: "2022" },
      { title: "Endometriosis: diagnosis and management", source: "NICE NG73", year: "2024" },
    ],
  },
  {
    slug: "agrili-adet",
    title: "Ağrılı adet (dismenore): Ne zaman değerlendirilmeli?",
    excerpt:
      "Hafif kramp sık görülür; günlük yaşamı durduran ağrı ise konuşulmalıdır.",
    category: "Adet Döngüsü",
    tags: ["ağrılı adet", "dismenore", "adet düzensizliği"],
    relatedSlugs: ["endometriozis", "adet-dongusu-temelleri"],
    readingMinutes: 5,
    publishedAt: "2026-02-20",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Adet sırasında kasık krampları sık görülür. Ağrının şiddeti, ilaçlara yanıtı ve yıllar içinde artıp artmadığı önemlidir.",
      "Ağrı her ay okul ya da işten alıkoyuyorsa, giderek kötüleşiyorsa, adet dışında da sürüyorsa ya da düzensiz veya çok yoğun kanama eşlik ediyorsa hekime başvurun. Endometriozis, miyom veya enfeksiyon gibi nedenler araştırılabilir.",
      "Isı uygulama ve hareket bazı kadınlarda rahatlatıcı olabilir. İlaç seçimi ve dozu için hekiminize ya da eczacınıza danışın.",
    ],
    references: [
      { title: "Dysmenorrhea and Endometriosis in the Adolescent", source: "ACOG Committee Opinion 760", year: "2018" },
    ],
  },
  {
    slug: "vajinal-enfeksiyonlar",
    title: "Vajinal akıntı ve enfeksiyonlar: Vajinit, mantar ve bakteriyel vajinoz",
    excerpt:
      "Her akıntı enfeksiyon değildir. Kaşıntı, koku ve renk değişikliğinde ne yapmalı? Gebelikte nelere dikkat?",
    category: "Jinekoloji",
    tags: ["vajinit", "vajinal enfeksiyon", "akıntı", "sistit"],
    relatedSlugs: ["jinekolojik-kontroller", "hpv"],
    readingMinutes: 6,
    publishedAt: "2026-02-24",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Vajinal akıntı, döngü boyunca miktar ve kıvam değiştirebilen doğal bir savunmadır. Kaşıntı, yanma, belirgin koku, renk değişikliği veya ağrı enfeksiyon belirtisi olabilir.",
      "Mantar enfeksiyonu, bakteriyel vajinoz ve cinsel yolla bulaşan enfeksiyonlar benzer şikâyetler yapabilir; tedavileri farklıdır. Bu yüzden tekrarlayan ya da emin olmadığınız durumlarda muayene önemlidir.",
      "Gebelikte akıntı artabilir; sulu gelme, kanama, kötü koku veya ateş varsa beklemeden başvurun. İdrarda yanma ve sık idrara çıkma sistit belirtisi olabilir; gebelikte ihmal edilmemelidir.",
    ],
    references: [
      { title: "Sexually Transmitted Infections Treatment Guidelines", source: "CDC", year: "2021" },
      { title: "Vaginitis in Nonpregnant Patients", source: "ACOG Practice Bulletin 215", year: "2020" },
    ],
  },
  {
    slug: "hpv",
    title: "HPV nedir? Aşı, smear ve genital siğil",
    excerpt:
      "HPV çok yaygındır ve çoğu kendiliğinden temizlenir. Tarama ve aşının yeri nedir?",
    category: "Koruyucu Sağlık",
    tags: ["HPV", "smear", "HPV aşısı", "genital siğil"],
    relatedSlugs: ["jinekolojik-kontroller", "vajinal-enfeksiyonlar"],
    readingMinutes: 6,
    publishedAt: "2026-03-02",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "HPV (insan papilloma virüsü) cinsel temasla bulaşan, çok yaygın bir virüstür. Enfeksiyonların çoğu bağışıklık sistemi tarafından kendiliğinden temizlenir.",
      "Bazı tipler genital siğillere, bazı yüksek riskli tipler ise uzun süre kalıcı olduğunda rahim ağzında hücre değişikliklerine yol açabilir. Smear ve HPV testi bu değişiklikleri erken yakalamak için yapılır.",
      "HPV aşısı en etkili korunma yollarından biridir; uygunluk ve zamanlama için hekiminize danışın. HPV pozitif sonuç bir kanser tanısı değildir; takip planını hekiminiz belirler.",
    ],
    references: [
      { title: "Human papillomavirus (HPV) and cervical cancer", source: "WHO", year: "2024" },
      { title: "Updated Cervical Cancer Screening Guidelines", source: "ACOG", year: "2021" },
    ],
  },
  {
    slug: "dogum-kontrol-yontemleri",
    title: "Doğum kontrol yöntemleri: Doğumdan sonra ve bebek planlamadan önce",
    excerpt:
      "Spiral, hap, kondom ve diğer yöntemler. Emzirirken neler konuşulur? Doğru yöntem kişiye göre seçilir.",
    category: "Koruyucu Sağlık",
    tags: ["doğum kontrol", "spiral", "emzirme", "aile planlaması"],
    relatedSlugs: ["lohusalik-nedir", "gebelik-oncesi-hazirlik"],
    readingMinutes: 6,
    publishedAt: "2026-03-06",
    author: "Editöryel ekip",
    reviewStatus: "editorial",
    body: [
      "Doğum kontrol yöntemleri hormonlu (hap, enjeksiyon, hormonlu spiral, implant) ve hormonsuz (bakırlı spiral, kondom) olarak gruplanabilir. Kondom aynı zamanda cinsel yolla bulaşan enfeksiyonlardan korur.",
      "Doğumdan sonra adet görmeden de gebe kalınabilir. Emziriyorsanız bazı yöntemler daha uygun olabilir; doğum sonrası kontrolde bu konuyu mutlaka konuşun.",
      "Sağlık geçmişiniz, sigara kullanımı, emzirme ve gelecekteki gebelik planınız yöntem seçimini etkiler. Yöntem seçimi ve başlama zamanı hekimle birlikte belirlenir.",
    ],
    references: [
      { title: "Medical eligibility criteria for contraceptive use", source: "WHO", year: "2015" },
      { title: "UK Medical Eligibility Criteria for Contraceptive Use", source: "FSRH", year: "2016" },
    ],
  },
];
