import type { ForumCategoryMeta, ForumPost } from "./types";

export const forumCategories: ForumCategoryMeta[] = [
  {
    slug: "bebek-planlayanlar",
    title: "Bebek Planlayanlar",
    description: "Gebelik öncesi hazırlık, bekleme süreci ve sabır üzerine sohbet.",
    tone: "bg-butter",
    icon: "sprout",
  },
  {
    slug: "gebelik-deneyimleri",
    title: "Gebelik Deneyimleri",
    description: "Hafta hafta değişimler, kontroller ve gündelik deneyimler.",
    tone: "bg-blush",
    icon: "baby",
  },
  {
    slug: "doguma-hazirlik",
    title: "Doğuma Hazırlık",
    description: "Hastane çantası, doğum planı ve doğum korkusu.",
    tone: "bg-peach",
    icon: "bag",
  },
  {
    slug: "lohusalik-emzirme",
    title: "Lohusalık & Emzirme",
    description: "Uykusuz geceler, emzirme ve duygusal toparlanma.",
    tone: "bg-sage",
    icon: "heart",
  },
  {
    slug: "anne-sagligi",
    title: "Anne Sağlığı",
    description: "Adet döngüsü, jinekolojik kontroller ve kendine bakım.",
    tone: "bg-sky",
    icon: "flower",
  },
  {
    slug: "menopoz",
    title: "Menopoz",
    description: "Perimenopoz, sıcak basmaları, uyku ve bu dönemin günlük hayata etkisi.",
    tone: "bg-[oklch(0.9_0.05_320)]",
    icon: "sun",
  },
  {
    slug: "gunluk-yasam",
    title: "Günlük Yaşam",
    description: "İş, ilişkiler, hareket ve küçük rutinler.",
    tone: "bg-muted",
    icon: "coffee",
  },
];

export const forumPosts: ForumPost[] = [
  {
    slug: "topluluk-kurallari-once-bunu-okuyun",
    category: "gebelik-deneyimleri",
    title: "Hoş geldiniz: Burası nasıl bir alan?",
    body: "Burası deneyim paylaşmak, birbirimize destek olmak ve ‘yalnız değilim’ demek için var. İlaç veya doz önerisi, başkasına tanı koymak ve kişisel iletişim bilgisi paylaşmak yasak. Acil bir durumda forum yerine 112’yi arayın.",
    author: "Moderasyon ekibi",
    anonymous: false,
    createdAt: "2026-06-01",
    pinned: true,
    tags: ["kurallar", "hoş geldin"],
    replies: [],
  },
  {
    slug: "planlama-surecinde-neler-yaptiniz",
    category: "bebek-planlayanlar",
    title: "Planlama sürecinde ilk neyi yaptınız?",
    body: "Eşimle bebek planlamaya karar verdik. Hekim kontrolü, aşılar, takviyeler… Nereden başlayacağımı bilemiyorum. Siz ilk adımda neler yaptınız? Doz önerisi değil, deneyim merak ediyorum.",
    author: "Ece",
    anonymous: false,
    createdAt: "2026-09-18",
    tags: ["planlama", "kontrol"],
    replies: [
      {
        author: "Zeynep T.",
        anonymous: false,
        createdAt: "2026-09-18",
        body: "Ben önce kadın doğum uzmanıyla gebelik öncesi görüşme yaptım. Kullandığım ilaçları listeleyip götürmek çok işe yaradı.",
      },
      {
        author: "Anonim",
        anonymous: true,
        createdAt: "2026-09-19",
        body: "Biz ikimiz de kontrol olduk. Partnerin de sürece katılması bana iyi hissettirdi.",
      },
    ],
  },
  {
    slug: "aylardir-deniyoruz-sabir",
    category: "bebek-planlayanlar",
    title: "Aylardır deniyoruz, sabır nasıl korunur?",
    body: "Her ay test yapıp hayal kırıklığı yaşamak beni yoruyor. Bu süreçte duygusal olarak nasıl ayakta kaldınız?",
    author: "Anonim",
    anonymous: true,
    createdAt: "2026-09-24",
    tags: ["duygusal destek", "bekleme"],
    replies: [
      {
        author: "Melis",
        anonymous: false,
        createdAt: "2026-09-25",
        body: "Test günlerini takvimden çıkarmak ve o günlere başka planlar koymak bana iyi geldi. Süre uzadıkça hekimle konuşmak da rahatlattı.",
      },
    ],
  },
  {
    slug: "ilk-trimester-yorgunluk",
    category: "gebelik-deneyimleri",
    title: "İlk trimesterde yorgunluk sizi de böyle mi yordu?",
    body: "8. haftadayım. Akşam 7’de uyuyası geliyor. İşten sonra hiçbir şey yapmak istemiyorum. Bu dönem nasıl geçti sizin için?",
    author: "Merve B.",
    anonymous: false,
    createdAt: "2026-09-03",
    stage: "8. hafta",
    tags: ["1. trimester", "yorgunluk"],
    replies: [
      {
        author: "Aylin",
        anonymous: false,
        createdAt: "2026-09-03",
        body: "Bende 12. haftaya kadar böyleydi. Küçük kestirmeler ve erken yatmak işime yaradı.",
      },
      {
        author: "Anonim",
        anonymous: true,
        createdAt: "2026-09-04",
        body: "Partnerimin yemek işini üstlenmesi büyük fark etti. Kendinize yüklenmeyin.",
      },
    ],
  },
  {
    slug: "ilk-tekmeler",
    category: "gebelik-deneyimleri",
    title: "İlk tekmeleri hissettiğiniz an",
    body: "19. haftadayım ve sanırım bugün ilk kez kıpırtı hissettim. Kelebek kanadı gibi. Sizin ilk hissettiğiniz an nasıldı?",
    author: "Gizem",
    anonymous: false,
    createdAt: "2026-09-27",
    stage: "19. hafta",
    tags: ["2. trimester", "bebek hareketleri"],
    replies: [
      {
        author: "Selin A.",
        anonymous: false,
        createdAt: "2026-09-27",
        body: "Ben de baloncuk patlıyor sandım! Sonra her akşam aynı saatte gelmeye başladı.",
      },
      {
        author: "Ece",
        anonymous: false,
        createdAt: "2026-09-28",
        body: "Okurken bile duygulandım. Tadını çıkarın.",
      },
    ],
  },
  {
    slug: "gebelikte-uyku-pozisyonu",
    category: "gebelik-deneyimleri",
    title: "Son haftalarda nasıl rahat uyuyorsunuz?",
    body: "31. haftadayım, yastık düzenim her gece değişiyor. Hangi destekler ve rutinler size iyi geldi?",
    author: "Anonim",
    anonymous: true,
    createdAt: "2026-09-30",
    stage: "31. hafta",
    tags: ["3. trimester", "uyku"],
    replies: [],
  },
  {
    slug: "hastane-cantasi-sade-liste",
    category: "doguma-hazirlik",
    title: "Hastane çantasında gerçekten işe yarayanlar",
    body: "İkinci doğumuma hazırlanıyorum. İlk seferinde çok fazla şey götürmüştüm. Sizin ‘keşke götürmeseydim’ listeniz var mı?",
    author: "Selin A.",
    anonymous: false,
    createdAt: "2026-09-12",
    stage: "36. hafta",
    tags: ["hastane çantası", "hazırlık"],
    replies: [
      {
        author: "Gamze",
        anonymous: false,
        createdAt: "2026-09-12",
        body: "Şarj kablosu, dudak kremi ve kendi yastık kılıfım çok işe yaradı. Hastanenin neler verdiğini önceden sorun.",
      },
    ],
  },
  {
    slug: "dogum-korkusu-paylasim",
    category: "doguma-hazirlik",
    title: "Doğum korkusunu kiminle konuştunuz?",
    body: "Doğum yaklaştıkça kaygım artıyor. Hekimime söylemekten çekiniyorum. Siz bu korkuyu kiminle ve nasıl konuştunuz?",
    author: "Anonim",
    anonymous: true,
    createdAt: "2026-09-21",
    stage: "34. hafta",
    tags: ["doğum korkusu", "duygusal destek"],
    replies: [
      {
        author: "Nil",
        anonymous: false,
        createdAt: "2026-09-22",
        body: "Kontrolde sorularımı yazıp götürdüm. Hekimim korkunun çok yaygın olduğunu söyleyince rahatladım.",
      },
    ],
  },
  {
    slug: "gece-uyanmalari",
    category: "lohusalik-emzirme",
    title: "Gece uyanmaları ve suçluluk",
    body: "Bebeğim 10 haftalık. Gece uyanınca ‘yetersiz anne’ gibi hissediyorum. Bunu kimse konuşmuyor gibi. Siz nasıl idare ettiniz?",
    author: "Anonim",
    anonymous: true,
    createdAt: "2026-09-15",
    tags: ["uyku", "duygusal destek"],
    replies: [
      {
        author: "Elif K.",
        anonymous: false,
        createdAt: "2026-09-15",
        body: "Suçluluk çok tanıdık. Nöbetleşe uyumak bize iyi geldi. İki haftadır hiç keyif alamıyorsanız bunu hekime söylemek de bakımın parçası.",
      },
    ],
  },
  {
    slug: "emzirmenin-ilk-haftasi",
    category: "lohusalik-emzirme",
    title: "Emzirmenin ilk haftası beklediğimden zor geçti",
    body: "Herkes ‘doğal gelir’ dedi ama ilk hafta ağladım. Emzirme danışmanından destek alan oldu mu, süreç nasıldı?",
    author: "Deniz T.",
    anonymous: false,
    createdAt: "2026-09-26",
    tags: ["emzirme", "destek"],
    replies: [],
  },
  {
    slug: "smear-korkusu",
    category: "anne-sagligi",
    title: "Doğumdan sonra smear yaptırmaya çekiniyorum",
    body: "Yıllardır erteledim. Ağrıdan değil, sonuçtan korkuyorum. Gidenler süreç nasıl geçti diye yazabilir mi?",
    author: "Duru",
    anonymous: false,
    createdAt: "2026-08-11",
    tags: ["kontrol", "smear"],
    replies: [
      {
        author: "Anonim",
        anonymous: true,
        createdAt: "2026-08-12",
        body: "Ben de ertelemiştim. İşlem kısaydı. Korkunun büyümesi beklemekle oldu.",
      },
    ],
  },
  {
    slug: "perimenopoz-mu-yasiyorum",
    category: "menopoz",
    title: "46 yaşındayım, adetlerim düzensizleşti. Perimenopoz mu?",
    body: "Son aylarda adetlerim bazen erken bazen geç geliyor, geceleri de terliyorum. Hekime gitmeden önce sizin bu dönemde neler yaşadığınızı merak ediyorum.",
    author: "Anonim",
    anonymous: true,
    createdAt: "2026-09-20",
    tags: ["perimenopoz", "adet düzensizliği"],
    replies: [
      {
        author: "Sevgi",
        anonymous: false,
        createdAt: "2026-09-21",
        body: "Bende de böyle başladı. Bir ay boyunca adet ve terleme günlerimi not edip hekime götürdüm, görüşme çok daha verimli geçti.",
      },
    ],
  },
  {
    slug: "sicak-basmalari-is-hayati",
    category: "menopoz",
    title: "Toplantı ortasında sıcak basması: Siz nasıl idare ediyorsunuz?",
    body: "İş yerinde birden kızarıp terliyorum ve çok utanıyorum. Kıyafet, ortam ya da rutin olarak işinize yarayan şeyler neler oldu?",
    author: "Hülya",
    anonymous: false,
    createdAt: "2026-09-29",
    tags: ["sıcak basması", "iş hayatı"],
    replies: [],
  },
  {
    slug: "hamileyken-calismak",
    category: "gunluk-yasam",
    title: "Hamileyken ofiste çalışmak: küçük kolaylıklar",
    body: "Masa başı çalışıyorum ve gün sonunda belim ağrıyor. İşte uyguladığınız küçük düzenlemeler neler?",
    author: "Nil",
    anonymous: false,
    createdAt: "2026-09-08",
    stage: "22. hafta",
    tags: ["iş hayatı", "günlük rutin"],
    replies: [
      {
        author: "Aylin",
        anonymous: false,
        createdAt: "2026-09-08",
        body: "Saat başı kalkıp kısa yürüyüş ve ayak altına küçük bir tabure. Ağrı artarsa hekime söylemek lazım tabii.",
      },
    ],
  },
];

export function lastActivity(post: ForumPost): string {
  return post.replies.at(-1)?.createdAt ?? post.createdAt;
}
