import type { Question } from "./types";

export const questions: Question[] = [
  {
    slug: "menopozda-gece-terlemeleri-normal-midir",
    title: "Menopozda gece terlemeleri normal midir?",
    body: "Son aylarda gece aniden terleyerek uyanıyorum. Bu menopozun bir parçası olabilir mi, yoksa başka bir şeye mi bakmalıyım?",
    category: "Menopoz",
    askedAt: "2026-08-12",
    askedBy: "Anonim",
    anonymous: true,
    isExpertAnswer: true,
    answeringProfessional: "Dr. İsmail Aykut",
    relatedArticleSlugs: ["sicak-basmasi-neden-olur", "menopozda-uyku", "perimenopoz-nedir"],
    answer:
      "Gece terlemesi, menopoz geçişinde sık anlatılan bir şikâyettir ve sıcak basmasının gece ortaya çıkan hali olabilir. Yine de terleme tiroit hastalıkları, enfeksiyon veya bazı ilaçlarla da görülebilir. Bu belirti menopoz döneminde görülebilir. Ancak farklı nedenleri de olabilir. Sıklık, ateş, kilo kaybı veya çarpıntı varsa hekiminizle yüz yüze değerlendirin. Bu yanıt tanı koymaz.",
  },
  {
    slug: "dogumdan-sonra-adet-ne-zaman-gelir",
    title: "Doğumdan sonra adet ne zaman geri gelir?",
    body: "Bebeğim 4 aylık. Emziriyorum, henüz adet görmedim. Bu normal mi?",
    category: "Doğum Sonrası",
    askedAt: "2026-07-28",
    askedBy: "Elif K.",
    anonymous: false,
    isExpertAnswer: false,
    answeringProfessional: "Editöryel ekip",
    relatedArticleSlugs: ["lohusalik-nedir", "emzirme", "adet-dongusu-temelleri"],
    answer:
      "Adetin dönüşü emzirme sıklığına, ek gıdaya ve kişiye göre değişir. Sık emziren bazı kadınlarda adet aylarca gecikebilir; bazılarında daha erken döner. Adet olmasa da yumurtlama olabilir, bu nedenle gebelikten korunma konuşulmalıdır. Yoğun kanama, ateş veya kötü kokulu akıntı varsa beklemeyin. Bu yanıt kişiye özel takip yerine geçmez.",
  },
  {
    slug: "gebelikte-hangi-belirtilerde-doktora",
    title: "Gebelikte hangi belirtilerde doktora başvurmalıyım?",
    body: "İlk gebeliğim. Ne zaman bekleyip ne zaman hemen gitmem gerektiğini karıştırıyorum.",
    category: "Gebelik",
    askedAt: "2026-06-18",
    askedBy: "Anonim",
    anonymous: true,
    isExpertAnswer: false,
    answeringProfessional: "Editöryel ekip",
    relatedArticleSlugs: ["gebelikte-ne-zaman-doktora", "gebelikte-mide-bulantisi"],
    answer:
      "Kanama, su gelmesi, şiddetli baş ağrısı, görme bulanıklığı, şiddetli karın ağrısı, ateş, bebek hareketlerinde azalma, nefes darlığı veya bayılma acil değerlendirme sebepleridir. Hafif bulantı veya yorgunluk sık görülür ama kusamayacak kadar şiddetliyse yine hekime sorun. Şüphede kalırsanız beklemeyin. Bu platform acil yardım sunmaz; 112’yi arayabilirsiniz.",
  },
  {
    slug: "dogum-belirtileri-nasil-anlasilir",
    title: "Doğum belirtilerini nasıl anlayabilirim?",
    body: "36. haftadayım. Kasılmalarım oluyor ama gerçek doğum mu emin değilim.",
    category: "Doğum",
    askedAt: "2026-08-02",
    askedBy: "Selin A.",
    anonymous: false,
    isExpertAnswer: false,
    answeringProfessional: "Editöryel ekip",
    relatedArticleSlugs: ["dogum-belirtileri", "hastane-cantasi"],
    answer:
      "Gerçek eylemde kasılmalar genelde sıklaşır, güçlenir ve dinlenmekle geçmez. Su gelmesi, kanama veya bebek hareketlerinde azalma varsa hekiminizin tarifine göre başvurun. Evde tek başına ‘eylem başladı’ tanısı koymak her zaman mümkün değildir. Emin değilseniz arayın. Bu bir eğitim yanıtıdır, muayene yerine geçmez.",
  },
  {
    slug: "sicak-basmasi-icin-ne-yapilir",
    title: "Sıcak basmaları için evde ne denenebilir?",
    body: "Gündüz iş yerinde aniden ateş basıyor gibi oluyor. İlaçsız bir şey var mı?",
    category: "Menopoz",
    askedAt: "2026-09-04",
    askedBy: "Anonim",
    anonymous: true,
    isExpertAnswer: false,
    answeringProfessional: "Editöryel ekip",
    relatedArticleSlugs: ["sicak-basmasi-neden-olur", "hormon-tedavisi-nedir"],
    answer:
      "Katmanlı giyinmek, ortamı serin tutmak, kafein/alkol/baharat tetikleyicilerini gözlemlemek ve düzenli hareket bazı kadınlarda şikâyeti azaltabilir. Bitkisel ürünleri ‘zararsız’ varsaymayın. Sık ve şiddetli ataklarda hekimle hormonlu veya hormonsuz seçenekler konuşulabilir. Kendi kendinize hormon veya ilaç başlatmayın.",
  },
  {
    slug: "hormon-tedavisi-herkes-icin-uygun-mu",
    title: "Menopozda hormon tedavisi herkes için uygun mudur?",
    body: "Arkadaşım hormon kullanıyor, bana da önerildi. Korkuyorum. Herkes kullanabilir mi?",
    category: "Hormonal Sağlık",
    askedAt: "2026-09-11",
    askedBy: "Anonim",
    anonymous: true,
    isExpertAnswer: true,
    answeringProfessional: "Dr. İsmail Aykut",
    relatedArticleSlugs: ["hormon-tedavisi-nedir", "menopozda-dogru-bilinen-yanlislar"],
    answer:
      "Hayır. Hormon tedavisi kişiye özel bir karardır. Yaş, menopozdan geçen süre, pıhtı, inme, meme kanseri öyküsü ve eşlik eden hastalıklar risk-fayda dengesini değiştirir. Birinin ilacı sizin ilacınız değildir. Kararı sizi muayene eden hekimle verin. Bu yanıt reçete niteliği taşımaz.",
  },
  {
    slug: "vajinal-kuruluk-menopoz",
    title: "Menopozda vajinal kuruluk için ne yapılabilir?",
    body: "İlişkide yanma oldu. Utandığım için söyleyemedim. Konuşulabilir bir şey mi?",
    category: "Jinekoloji",
    askedAt: "2026-08-22",
    askedBy: "Anonim",
    anonymous: true,
    isExpertAnswer: false,
    answeringProfessional: "Editöryel ekip",
    relatedArticleSlugs: ["menopozda-cinsel-saglik", "pelvik-saglik"],
    answer:
      "Evet, konuşulabilir ve sık görülür. Östrojen azalması dokuyu daha ince ve daha az kaygan hale getirebilir. Nemlendirici ve kayganlaştırıcı bazı kadınlara yardım eder; lokal tedaviler hekimle planlanır. Kanama, akıntı veya ateş varsa muayene şarttır. Utanç, bakımın önünde durmak zorunda değil.",
  },
  {
    slug: "gebelikte-folik-asit",
    title: "Gebelik planlarken folik asit ne zaman başlar?",
    body: "Çocuk istiyoruz. Folik asidi şimdiden mi almalıyım?",
    category: "Gebelik",
    askedAt: "2026-05-09",
    askedBy: "Deniz T.",
    anonymous: false,
    isExpertAnswer: false,
    answeringProfessional: "Editöryel ekip",
    relatedArticleSlugs: ["gebelik-oncesi-hazirlik", "gebelikte-beslenme"],
    answer:
      "Birçok kadında folik asit, gebelikten önce başlanması önerilen bir destektir çünkü nöral tüp gelişimi çok erken dönemde olur. Doz sizin öykünüze göre değişebilir (örneğin önceki nöral tüp defekti, epilepsi, diyabet). Hekiminizle mevcut ilaçlarınızı da konuşun. Bu yanıt doz reçetesi değildir.",
  },
];
