import type { Topic } from "./types";

export const topics: Topic[] = [
  {
    slug: "gebelik-planlamasi",
    title: "Gebelik planlaması",
    description: "Gebelik öncesi kontroller, folik asit ve yaşam tarzı.",
    href: "/gebelik#oncesi",
    stage: "gebelik",
    keywords: ["gebelik planlama", "folik asit", "aşı", "ilaç"],
  },
  {
    slug: "1-trimester",
    title: "1. trimester",
    description: "İlk haftalar, belirtiler, bulantı ve yorgunluk.",
    href: "/gebelik#trimester-1",
    stage: "gebelik",
    keywords: ["bulantı", "gebelik belirtileri", "ilk kontroller"],
  },
  {
    slug: "2-trimester",
    title: "2. trimester",
    description: "Bebeğin gelişimi, anne vücudundaki değişiklikler.",
    href: "/gebelik#trimester-2",
    stage: "gebelik",
    keywords: ["ikinci trimester", "beslenme", "günlük yaşam"],
  },
  {
    slug: "3-trimester",
    title: "3. trimester",
    description: "Doğuma hazırlık, belirtiler ve sık sorulanlar.",
    href: "/gebelik#trimester-3",
    stage: "gebelik",
    keywords: ["doğuma hazırlık", "hastane çantası", "doğum planı"],
  },
  {
    slug: "dogum-belirtileri",
    title: "Doğum belirtileri",
    description: "Doğum ne zaman başlar, kasılmalar nasıl anlaşılır?",
    href: "/yazilar/dogum-belirtileri",
    stage: "dogum",
    keywords: ["doğum belirtileri", "su gelmesi", "kasılma"],
  },
  {
    slug: "dogum-yontemleri",
    title: "Doğum yöntemleri",
    description: "Vajinal doğum ve sezaryen nasıl konuşulur?",
    href: "/yazilar/vajinal-dogum-ve-sezaryen",
    stage: "dogum",
    keywords: ["vajinal doğum", "normal doğum", "sezaryen"],
  },
  {
    slug: "gebelikte-riskler",
    title: "Gebelikte takip gerektiren durumlar",
    description: "Preeklampsi, gebelik şekeri, erken doğum ve dış gebelik.",
    href: "/yazilar/preeklampsi",
    stage: "gebelik",
    keywords: ["preeklampsi", "gebelik şekeri", "diyabetik gebelik", "erken doğum", "dış gebelik", "ektopik"],
  },
  {
    slug: "jinekolojik-sorunlar",
    title: "Sık görülen jinekolojik sorunlar",
    description: "PKOS, miyom, endometriozis, ağrılı adet, vajinal enfeksiyonlar ve HPV.",
    href: "/kadin-sagligi",
    stage: "kadin-sagligi",
    keywords: ["PKOS", "polikistik over", "miyom", "endometriozis", "adenomyozis", "dismenore", "vajinit", "HPV", "sistit"],
  },
  {
    slug: "lohusalik",
    title: "Lohusalık",
    description: "Doğumdan sonraki fiziksel ve duygusal değişimler.",
    href: "/yazilar/lohusalik-nedir",
    stage: "dogum-sonrasi",
    keywords: ["lohusalık", "emzirme", "kanama"],
  },
  {
    slug: "perimenopoz",
    title: "Perimenopoz",
    description: "Menopoza geçiş dönemini anlamak.",
    href: "/yazilar/perimenopoz-nedir",
    stage: "perimenopoz",
    keywords: ["perimenopoz", "adet düzensizliği"],
  },
  {
    slug: "sicak-basmasi",
    title: "Sıcak basmaları",
    description: "Sıcak basması neden olur, ne zaman hekime gidilir?",
    href: "/yazilar/sicak-basmasi-neden-olur",
    stage: "menopoz",
    keywords: ["sıcak basması", "gece terlemesi"],
  },
  {
    slug: "hormon-tedavisi",
    title: "Hormon tedavisi",
    description: "Kimler için düşünülür, kimler için uygun olmayabilir?",
    href: "/yazilar/hormon-tedavisi-nedir",
    stage: "menopoz",
    keywords: ["hormon tedavisi", "MHT"],
  },
  {
    slug: "menopoz-sonrasi-saglik",
    title: "Menopoz sonrası sağlık",
    description: "Kemik, kalp-damar ve koruyucu bakım.",
    href: "/menopoz#sonrasi",
    stage: "menopoz-sonrasi",
    keywords: ["kemik", "kalp", "tarama"],
  },
];
